INSERT INTO `filters` (category, filter, label) VALUES 
('Cistella de la compra','bon preu',''),
('Cistella de la compra','consum',''),
('Salut','Sara Tomás',''),
('Comissions','n26',''),
('Cistella de la compra','macxipa',''),
('Rosa','Rosa',''),
('Prestecs','cofidis',''),
('Salut','farmacia',''),
('Casa - Compra','Hipoteca',''),
('Cistella de la compra','carn',''),
('Oci','netflix',''),
('Llar - Petites despeses','bazar',''),
('Amazon','amazon',''),
('Administració','ajunt bcn',''),
('Restauració','cafe',''),
('Cistella de la compra','fruits',''),
('Transport','on aparcar',''),
('Oci','spotify',''),
('Restauració','pick and pay',''),
('Nòmina','userzoom',''),
('Restauració','food',''),
('Cistella de la compra','torres',''),
('Donacions','marato',''),
('Cistella de la compra','peix',''),
('Cistella de la compra','condis',''),
('Llar - Petites despeses','market stacolom',''),
('Cistella de la compra','SANTA COLOMA GRAMENET',''),
('Cistella de la compra','PRIMAPRIX SANTA COLOMA',''),
('Restauració','ENTREPANES DIAZ',''),
('Traspassos','De Cuenta Principal a Estalvis',''),
('Aila','Aila',''),
('Ni idea','CAJA DE AH.Y PENSIONES',''),
('Amazon','AMZN Mktp',''),
('Traspassos','XAVIER CAROL ROSELL',''),
('Cistella de la compra','ALIMENT',''),
('Traspassos','De Estalvis a Cuenta Principal',''),
('Cistella de la compra','ENRIQUE TOMAS',''),
('Transport','TMB APP',''),
('Amazon','AMZ*',''),
('Roba i complements','DECATHLON',''),
('Salut','CLINICA DENTAL',''),
('Llar - Petites despeses','CROWN ROYAL MOBILE SHO',''),
('Llar - Petites despeses','CRACK STA COLOMA',''),
('Donacions','REDONDEO',''),
('Donacions','ASSEMBLEA NACIONAL CATALANA',''),
('Restauració','UDON',''),
('Transport','INFRASTRUC VIARIES',''),
('Transport','INVICAT',''),
('Donacions','PERE VIRGILI',''),
('Roba i complements','WISH',''),
('Roba i complements','ZALANDO',''),
('Ni idea','LA CAIXA',''),
('Caixer','B.B.V.A.',''),
('Caixer','BANCOSABADELL',''),
('Transport','E.S.',''),
('Cistella de la compra','supermercat',''),
('Restauració','doner',''),
('Restauració','JUSTEAT',''),
('Oci','CINE',''),
('Donacions','Assoc Malalts Gaucher',''),
('Oci','FEVER',''),
('Transport','PARKING',''),
('Cistella de la compra','VINNALIUM',''),
('Cistella de la compra','LA PARADETA',''),
('Salut','ASISTENCIA SANITARIA C',''),
('Cistella de la compra','VERDURA',''),
('Restauració','MUSTA SHAWARMA',''),
('Oci','LOTERIES DE CATALUNYA',''),
('Traspassos','Transferencia A Favor De Xavier Carol',''),
('Cistella de la compra','EMBUTIDO',''),
('Transport','UBER',''),
('Transport','Cabify',''),
('Oci','AIRBNB',''),
('Oci','FLORES',''),
('Traspassos','De Estalvis a Compte Principal',''),
('Donacions','Acnur',''),
('Donacions','Recerca',''),
('Serveis','Jazztel',''),
('Serveis','Repsol',''),
('Pensió','Pension Seguridad Social',''),
('Oci','hbomax',''),
('Donacions','Plataforma Per La Llengua',''),
('Restauració','RESTAURANT',''),
('Cistella de la compra','CASA PAREDES',''),
('Comunitat de veïns','Recibo Generalitat 68',''),
('Assegurances','Santander Generales Mi Hogar Santander',''),
('Salut','MONICA SANCHEZ GIL',''),
('Restauració','LA CARAVANA',''),
('Oci','Render.com',''),
('Oci','NAVARROVERD, S.L.',''),
('Comunitat de veïns','Recibo Generalitat De Catalunya',''),
('Llar - Petites despeses','LM LA MAQUINISTA','Leroy Merlin'),
('Inversió','Gaesco',''),
('Serveis','Aguapur',''),
('Serveis','Fibracat',''),
('Serveis','Totalenergies',''),
('Cistella de la compra','LA SIRENA',''),
('Cistella de la compra','KATIA',''),
('Oci','FLORS',''),
('Cistella de la compra','SUPERMERCADO',''),
('Restauració','PASTISSERIA',''),
('Llar - Grans despeses','TRASOFA COMERCIAL DE MUEBLES SL',''),
('Llar - Grans despeses','todoplano',''),
('Roba i complements','TIMBERLAND',''),
('Transport','RENFE',''),
('Oci','REGALS',''),
('Transport','GPV NUDO DE LA TRINIDA',''),
('Caixer','ATM',''),
('Oci','INTERDOMINIOS',''),
('Transport','ITV',''),
('Transport','A.C.E.S.A',''),
('Donacions','FUND HOSP UNI VALL DHE',''),
('Restauració','VIENA',''),
('Llar - Petites despeses','FERRETERIA',''),
('Serveis','BITWARDEN',''),
('Donacions','FUNDACIO',''),
('Restauració','MUSTA SHAQARMA',''),
('Traspassos','CAROL ROSELL XAVIER',''),
('Altres despeses','PAYPAL *CMFLTD',''),
('Altres despeses','REGISTRE_CONSELL',''),
('Altres despeses','SE CORREOS Y TELEGRAFO',''),
('Transport','DPC OIL 33, S.L.',''),
('Oci','TINDER',''),
('Casa - Compra','Bankinter',''),
('Donacions','ASOCIACION ESPANOLA DE GAUCHER',''),
('Transport','PETROCAT',''),
('Traspassos','De Pis a Compte Principal',''),
('Traspassos','Evo',''),
('Salut','GENERAL OPTICA',''),
('Transport','ALLIANZ',''),
('Serveis','LOWI',''),
('Traspassos','Xavi Santander',''),
('Traspassos','De Estalvi a Compte Principal',''),
('Traspassos','De Compte Principal',''),
('Transport','HOMECARWASH',''),
('Donacions','OMNIUM',''),
('Transport','BENZINERA',''),
('Restauració','UGARIT',''),
('Llar - Petites despeses','BRILLANT SANTA COLOMA',''),
('Estafa','Coinbase',''),
('Donacions','AEEFEG',''),
('Serveis','Recibo Alta Tecnologia En Comunicacions',''),
('Oci','ETORO',''),
('Cistella de la compra','Nespresso',''),
('Donacions','ARRODONIMENT','ARRODONIMENT'),
('Cistella de la compra','FORN DEL BARRI','FORN DEL BARRI'),
('Administració','AJUNTAMENT','AJUNTAMENT'),
('Transport','METRO BARCELONA','METRO BARCELONA'),
('Salut','DUET CAN ZAM, SA','DUET CAN ZAM, SA'),
('Administració','AGENCIA TRIBUTARIA','AGENCIA TRIBUTARIA'),
('Prestecs','Liquidacion Periodica Prestamo 0049 5316 103 0670104','Hipoteca pis'),
('Transport','ORANGE CAR SUPLLY BARC','Benzinera B-OIL'),
('Serveis','Recibo Aigues De Barcelona Subministrament','Aigua'),
('Serveis','Recibo Tractament I Seleccio De Residus','Electricitat'),
('Cistella de la compra','AMETLLER','CASA AMETLLER'),
('Llar - Petites despeses','ESPAI SELECCIO','ESPAI SELECCIO'),
('Serveis','GOOGLE STORAGE','GOOGLE STORAGE'),
('Restauració','GRANIER','GRANIER'),
('Llar - Petites despeses','PAPIROS PEN SL','PAPIROS PEN SL'),
('Transport','PK.GRAN VIA CARLES III','PK.GRAN VIA CARLES III'),
('Llar - Grans despeses','IKEA BADALONA HFB','IKEA BADALONA HFB'),
('Traspassos','WESMARTPARK','WESMARTPARK'),
('Salut','FCIA','Farmàcia'),
('Salut','MES SALUT','MES SALUT'),
('Advocats','Mireia Largo','Mireia Largo'),
('Cistella de la compra','LINDT','XOCOLATAAA'),
('Llar - Petites despeses','CA LAGUSTI','Jardineria'),
('Llar - Petites despeses','DEBISUAL','Fotocopies, etc...'),
('Oci','Compra Paypal *max','HBOMAX'),
('Transport','PCAT POTOSI','Rentat cotxe'),
('Serveis','Recibo Aqualogy Solutions','Impost revolucionari de l\'Aigua'),
('Administració','impost','Impostos');
