# syntax=docker/dockerfile:1.7-labs
FROM node:20

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y default-mysql-client

WORKDIR /server
COPY --exclude=node_modules ./server/ .
RUN npm install

EXPOSE 3000

CMD ["npm", "start"]
