FROM node:20

WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/xcarol/wmm.git .

WORKDIR /app/client
RUN npm install
RUN npm run build

EXPOSE 8080

CMD ["npm", "start"]
