/* This file was generated by 'vue add axios' command */
/* Therefore instead of fixing lint errors we prefer to disable them */
/* eslint-disable func-names */
/* eslint-disable prefer-arrow-callback */
/* eslint-disable no-param-reassign */
/* eslint-disable no-unused-vars */

import axios from 'axios';

// Full config:  https://github.com/axios/axios#request-config
const baseURL = import.meta.env.VITE_API_URL || 'http://127.0.0.1:3000';

const AxiosPlugin = {
  install(app, options) {
    const _axios = axios.create({
      baseURL: app.config.globalProperties.VITE_API_URL || baseURL,
    });

    _axios.interceptors.request.use(
      function (_config) {
        _config.headers = {
          'Content-Type': 'application/json',
        };
        return _config;
      },
      function (error) {
        // Do something with request error
        console.log(error);
        return Promise.reject(error);
      },
    );
    
    // Add a response interceptor
    _axios.interceptors.response.use(
      function (response) {
        // Do something with response data
        return response;
      },
      function (error) {
        return Promise.reject(error);
      },
    );
        
    app.config.globalProperties.axios = _axios;
  },
};

export default AxiosPlugin;
